import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react'


export default function Home({content}) {

  const [realm, setRealm] = useState(4728); //default realm set to benediction
  const [auctionHouse, setAH] = useState(7); //default ah set to neutral
  const [listings, setListings] = useState();
  const [lastModified, setLastMod] = useState();
  // const [totalItems, setTotalItems] = useState();
  // const [uniqueCount, setUniqueCount] = useState();
  // const [isLoading, setIsLoading] = useState();

  useEffect(() => {
    async function setData(){
      setLastMod(data[realm][auctionHouse].lastModified);
      setListings(data[realm][auctionHouse].items);
      // console.log(data[realm][auctionHouse]);
      // // setTotalItems(data[realm][auctionHouse].total);
      // // setUniqueCount(data[realm][auctionHouse].uniqueItems);
      // // console.log(data.items);
      // console.log(data[realm][auctionHouse].items);
      // console.log(listings);
      // console.log("BREAKER");
  }
  setData();
  },[realm, auctionHouse]);



  const {realms, auctionHouses, data, itemInfo} = content;
  const {names, icons} = itemInfo;
  // console.log(names);
  // console.log(realms)
  // console.log(auctionHouse)
  // console.log(data)

  let realmsArr = [];
  const realmKeys = Object.keys(realms);
  realmKeys.forEach((realmKey) => {
    realmsArr.push(
      <div key = {realmKey} onClick={() => setRealm(realmKey) }>{realms[realmKey]}</div>
    )
  })

  let ahArr = [];
  const ahKeys = Object.keys(auctionHouses);
  ahKeys.forEach((ahKey) => {
    ahArr.push(
      <div key = {ahKey} onClick={() => setAH(ahKey) }>{auctionHouses[ahKey]}</div>
    )
  })

let postsArr = [];
// console.log(data[realm][auctionHouse].items);
// console.log(listings);
if(listings){
  Object.keys(listings).forEach( (item) => {
    if(item)
    {
      if(names[item])
      {
        if(names[item] !== "Deprecated")
        {
          postsArr.push(
            <div key = {item} className= {styles.postsContainer}>
            <a href={"https://tbc.wowhead.com/item="+item}><img src={icons[item]}/></a>
            <a className = {styles.itemName} href={"https://tbc.wowhead.com/item="+item}>{names[item]}</a>
            <p>Buyout Price: {intToGold(listings[item].toFixed(4))}</p> 
          </div>)
        }
      }
      else
      {
        console.log(item);
      }
    }
  })
}


return (
    <div className={styles.container}>
      <Head>
        <title>Raider Auction House</title>
        <meta name="description" content="Generated by create next app" />
        <script src="https://wow.zamimg.com/widgets/power.js"></script>
        <link type="text/css" href="https://wow.zamimg.com/css/basic.css?16" rel="stylesheet"></link> 
      </Head>

      <main className={styles.main}>
      <div className= {styles.dropdown}>
        <button className ={styles.dropbtn}>Realm Select</button>
        <div className={styles.dropdownContent}>
            {realmsArr}
        </div>
      </div>
      <div className= {styles.dropdown}>
        <button className ={styles.dropbtn}>Auction House Select</button>
        <div className={styles.dropdownContent}>
            {ahArr}
        </div>
      </div>
      <div className={styles.main} >
        <h1>{realms[realm]}{auctionHouses[auctionHouse]}Auction House</h1>
        <h1>Last Updated: {lastModified} </h1>
        {postsArr}
      </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}


export const getStaticProps = async () => {
  let combinedData;
  try{
    const startTime = Date.now();
    const realmRes = await fetch('http://localhost:3000/api/realms');
    const realmData = await realmRes.json();

    let realmHash = {};
    realmData && realmData.map((realm) => {
      const {id, name} = realm
      realmHash[id] = name
      return;
    })
    const ahHash = {2:"Alliance",6:"Horde",7:"Neutral"};

    const realmKeys = Object.keys(realmHash);
    const ahKeys = Object.keys(ahHash);
    let data = {};
    data = realmKeys && await Promise.all(realmKeys.map(async (realmKey) => {
      let auctionHouseData = ahKeys && await Promise.all(ahKeys.map(async (ahKey) => {
        const auctionParams = new URLSearchParams({
          realmKey,
          ahKey,
        }).toString();
        const auctionRes =  auctionParams && await fetch(`http://localhost:3000/api/auctions?${auctionParams}`);
        const auctionData = await auctionRes.json();
        return auctionData 
      }))
      const realmData = {}
      realmData[realmKey] = auctionHouseData;
      return realmData
    }))

    let reformattedData = {} //reformatting data, removing arrays from promise
    data.forEach( (realmData) => {
      let realmAuctionData = {}
      let realmID;
      Object.keys(realmData).forEach((realmKey) => {
        realmAuctionData["2"] = realmData[realmKey][0];
        realmAuctionData["6"] = realmData[realmKey][1];
        realmAuctionData["7"] = realmData[realmKey][2];
        realmID = realmKey;
      });
      reformattedData[realmID] = realmAuctionData;
    })

    const allItemInfoRes = await fetch('http://localhost:3000/api/allItemInfo');
    const allItemInfoData = await allItemInfoRes.json();
    const endTime = Date.now();
    combinedData = {
      realms: realmHash,
      auctionHouses: ahHash,
      data: reformattedData,
      itemInfo: allItemInfoData,
    }
    console.log(`Elapsed time ${endTime - startTime}`)
  }
  catch (error) {
    console.log('Error getting data', error);
  }

  // [{'benediction':{'2':{}, '6': {}, '7':{}}}.]
  return {
    props: {
      content: combinedData
    },
    revalidate: 60
  }
}

export const intToGold = (int) =>
{
  const valueArr = int.toString().split(".");
  const gold = valueArr[0]
  const silver = valueArr[1].substr(0,2);
  const copper = valueArr[1]. substr(2)

  return gold + "g " + silver + "s " + copper +"c"
}

