import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import Image from 'next/image'

const fetcher = (url) => fetch(url).then((res) => res.json())
const fetcher2 = (url) => fetch(url).then((res) => res.json())

export default function Home({listings}) {
  let map = new Map();
  const posts = [];
  for(let i = 0; i<listings.auctions.length-1;i++)
  {
    if(!map.has(listings.auctions[i].item.id))
    {
      map.set(listings.auctions[i].item.id, listings.auctions[i].buyout/listings.auctions[i].quantity/10000);
    }
    else
    {
      if(map.get(listings.auctions[i].item.id) > listings.auctions[i].buyout/listings.auctions[i].quantity/10000 && listings.auctions[i].buyout > 0) // buyouts are sometimes = 0
      {
        // console.log(data.auctions[i].buyout + "           " + map.get(data.auctions[i].item.id));
        map.set(listings.auctions[i].item.id, listings.auctions[i].buyout/listings.auctions[i].quantity/10000);
        // console.log(map.get(data.auctions[i].item.id));
      }
    }
  }
  for (const [key,value] of map.entries()) {
    let itemName = "loading....";
    let itemIconURL = "https://wow.zamimg.com/images/wow/icons/large/inv_misc_questionmark.jpg";
    const { data : name, error : nameError } = useSWR('https://us.api.blizzard.com/data/wow/item/'+key+'?namespace=static-classic-us&locale=en_US&access_token=USwMmO5QuXAeExdcWCOFcaUn1SorqzoyRJ', fetcher)
    const { data : icon, error : iconError } = useSWR('https://us.api.blizzard.com/data/wow/media/item/'+key+'?namespace=static-classic-us&locale=en_US&access_token=USwMmO5QuXAeExdcWCOFcaUn1SorqzoyRJ', fetcher2)
    if(name != undefined)
    {
      itemName = name.name;
    }
    if(icon != undefined)
    {
      itemIconURL = icon.assets[0].value;
    }
    posts.push(
      <div key={key}>
        <a href={"https://www.wowhead.com/item="+key}><img src={itemIconURL}/></a>
        <a href={"https://www.wowhead.com/item="+key}>{itemName}</a>
        Buyout Price: {intToGold(value.toFixed(4))}
      </div>
    )
    break;
  }
  // console.log(listings.lastModified);
  return (
    <div className={styles.container}>
      <Head>
        <title>Raider Auction House</title>
        <meta name="description" content="Generated by create next app" />
        <script></script>
        <script src="https://wow.zamimg.com/widgets/power.js"></script>
        <link type="text/css" href="https://wow.zamimg.com/css/basic.css?16" rel="stylesheet"></link> 
      </Head>

      <main className={styles.main}>
        <div>
          <h1>Lastest Price Update: {listings.lastModified} </h1>
          {posts}
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}


export const getStaticProps = async () => {
  let data;
  let lastMod;
  try{
    const res = await fetch("https://us.api.blizzard.com/data/wow/connected-realm/4372/auctions/2?namespace=dynamic-classic-us&locale=en_US&access_token=USwMmO5QuXAeExdcWCOFcaUn1SorqzoyRJ");
    data = await res.json();
    lastMod = res.headers.get('last-modified');
    // console.log(lastMod);
  }
  catch (error) {
    console.log('Error getting data', error)
  }
  return {
    props: {
      listings : data,
      lastModified : lastMod,
    },
    revalidate: 5,
  }
}

export const intToGold = (int) =>
{
  const valueArr = int.toString().split(".");
  const gold = valueArr[0]
  const silver = valueArr[1].substr(0,2);
  const copper = valueArr[1]. substr(2)

  return gold + "g " + silver + "s " + copper +"c"
}


