import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home({item}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div>
      <p>{item.auctions[0].item.id}</p>
      <p>{item.auctions[0].bid}</p>
      <p>{item.auctions[0].buyout}</p>
      </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}


export const getStaticProps = async() => {
  const res = await fetch("https://us.api.blizzard.com/data/wow/connected-realm/4372/auctions/2?namespace=dynamic-classic-us&locale=en_US&access_token=USwMmO5QuXAeExdcWCOFcaUn1SorqzoyRJ")
  const data = await res.json();
  // console.log(data.auctions.length);
  // create a map where each key(data.auctions[i].item.id) with a value of min buyout.
  let map = new Map();
  for(let i = 0; i<data.auctions.length-1;i++)
  {
    if(!map.has(data.auctions[i].item.id))
    {
      map.set(data.auctions[i].item.id, data.auctions[i].buyout);
    }
    else
    {
      if(map.get(data.auctions[i].item.id) > data.auctions[i].buyout)
      {
        // console.log(data.auctions[i].buyout + "           " + map.get(data.auctions[i].item.id));
        map.set(data.auctions[i].item.id, data.auctions[i].buyout);
        // console.log(map.get(data.auctions[i].item.id));
      }
    }
  }
  // console.log(map);
  return {
    props: {item : data}
  }
}


